---
spring:
  data:
    rest:
      base-path: crud

challonge:
  host: api.challonge.com
  api-key: this-is-the-api-key-from-challonge

---
spring:
  profiles: test
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      # use this to create an h2-only sql admin console within the application
      enabled: true
      # go to http://{host}/{path} to see the sql admin console
      path: /h2-console
challonge:
  api-key: this-is-a-test-api-key

---
spring:
  profiles: local
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # url specifies a file name, appended with ".mv.db"
    # jdbc:h2:{filename}
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      # use this to create an h2-only sql admin console within the application
      enabled: true
      # go to http://{host}/{path} to see the sql admin console
      path: /h2-console

---
spring:
  profiles: integration-test

---
spring:
  profiles: dev

---
spring:
  profiles: qa

---
spring:
  profiles: prod
