spring:
  profiles: local
  
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:
    username:
    password:
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  
  h2:
    console:
      # use this to create an h2-only sql admin console within the application
      enabled: true
      # go to http://{host}/{path} to see the sql admin console
      path: /h2-console

challonge:
  host: api.challonge.com
  api-key: this-is-the-api-key-from-challonge
