spring:
  profiles: test
  
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    # url specifies a file name, appended with ".mv.db"
    # jdbc:h2:{filename}
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  
  h2:
    console:
      # use this to create an h2-only sql admin console within the application
      enabled: true
      # go to http://{host}/{path} to see the sql admin console
      path: /h2-console

  security:
    enabled: true
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://dev-66577045.okta.com/oauth2/default"
          jwk-set-uri: "https://dev-66577045.okta.com/oauth2/default/v1/keys"

challonge:
  host: api.challonge.com
  api-key: this-is-a-test-api-key
