server:
  port: ${PORT}

spring:
  profiles: heroku
  
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: (set this in heroku)
    username: (set this in heroku)
    password: (set this in heroku)
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  
  security:
    enabled: true
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://dev-66577045.okta.com/oauth2/default"
          jwk-set-uri: "https://dev-66577045.okta.com/oauth2/default/v1/keys"
          
challonge:
  host: api.challonge.com
  api-key: (set this in heroku)
